version: "3"
services:
  mysql:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - "./mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "dockerLiu"
      MYSQL_USER: "root"
  app:
    image: maven:3.5-jdk-8
    restart: always
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    command: mvn clean spring-boot:run
    ports:
      - "8088:8088"
  test:
    image: alpine:latest
    command: "ping mysql"